version: '3'

services:
  offpeak:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./secrets:/secrets
    ports:
      - 3000:8080
    env_file:
      - ./docker.env
