name: Build and Push Docker Image

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Git setup
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: Generate Version
        id: version-step
        run: echo "version=g$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Node.js environment
        uses: actions/setup-node@v3.8.1

      - name: Build Go sources
        run: |
          GOARCH=amd64 GOOS=linux go build -o bin/offpeak ./server/cmd/*.go

      - name: Yarn install
        working-directory: app
        run: |
          yarn install

      - name: Vite build
        working-directory: app
        run: |
          yarn run build

      - name: Vite Test
        working-directory: app
        run: |
          yarn run test
